-- ============================================================================
-- Matutinas — Segundo semestre 2026 (Julio a Diciembre)
-- Versión bíblica: Reina-Valera 1909 (RV1909, dominio público)
-- Texto de los versículos: api.getbible.net (traducción "valera")
-- Generado por db/_build_sem2.py — Total: 184 días
-- ============================================================================

create table if not exists versiculos_dia (
  id                bigint generated always as identity primary key,
  fecha             date    not null unique,
  dia_semana        text    not null,
  tema              text    not null,
  cita              text    not null,
  libro             text    not null,
  capitulo          int     not null,
  versiculo_inicio  int     not null,
  versiculo_fin     int,
  texto             text,
  semestre          text    not null default '2026-1'
);

insert into versiculos_dia
  (fecha, dia_semana, tema, cita, libro, capitulo, versiculo_inicio, versiculo_fin, texto, semestre)
values
-- ===================== JULIO 2026 =====================
('2026-07-01','Miércoles','Compasivos','2 Timoteo 3:16, 17','2 Timoteo',3,16,17,'Toda Escritura es inspirada divinamente y útil para enseñar, para redargüir, para corregir, para instituir en justicia, Para que el hombre de Dios sea perfecto, enteramente instruído para toda buena obra.','2026-2'),
('2026-07-02','Jueves','Compasivos','1 Juan 2:6','1 Juan',2,6,NULL,'El que dice que está en él, debe andar como él anduvo.','2026-2'),
('2026-07-03','Viernes','Compasivos','Judas 1:24','Judas',1,24,NULL,'A aquel, pues, que es poderoso para guardaros sin caída, y presentaros delante de su gloria irreprensibles, con grande alegría,','2026-2'),
('2026-07-04','Sábado','Compasivos','Romanos 14:1','Romanos',14,1,NULL,'Recibid al flaco en la fe, pero no para contiendas de disputas.','2026-2'),
('2026-07-05','Domingo','Rectos','Salmos 7:10','Salmos',7,10,NULL,'Mi escudo está en Dios, que salva á los rectos de corazón.','2026-2'),
('2026-07-06','Lunes','Rectos','Salmos 32:11','Salmos',32,11,NULL,'Alegraos en Jehová, y gozaos, justos: y cantad todos vosotros los rectos de corazón.','2026-2'),
('2026-07-07','Martes','Rectos','Salmos 36:10','Salmos',36,10,NULL,'Extiende tu misericordia á los que te conocen, y tu justicia á los rectos de corazón.','2026-2'),
('2026-07-08','Miércoles','Rectos','Proverbios 2:7','Proverbios',2,7,NULL,'El provee de sólida sabiduría á los rectos: es escudo á los que caminan rectamente.','2026-2'),
('2026-07-09','Jueves','Rectos','Proverbios 2:21','Proverbios',2,21,NULL,'Porque los rectos habitarán la tierra, y los perfectos permanecerán en ella;','2026-2'),
('2026-07-10','Viernes','Rectos','Proverbios 14:11','Proverbios',14,11,NULL,'La casa de los impíos será asolada: mas florecerá la tienda de los rectos.','2026-2'),
('2026-07-11','Sábado','Rectos','Proverbios 15:8','Proverbios',15,8,NULL,'El sacrificio de los impíos es abominación á Jehová: mas la oración de los rectos es su gozo.','2026-2'),
('2026-07-12','Domingo','El Sábado','Mateo 12:8','Mateo',12,8,NULL,'Porque Señor es del sábado el Hijo del hombre.','2026-2'),
('2026-07-13','Lunes','El Sábado','Marcos 2:27','Marcos',2,27,NULL,'También les dijo: El sábado por causa del hombre es hecho; no el hombre por causa del sábado.','2026-2'),
('2026-07-14','Martes','El Sábado','Marcos 2:28','Marcos',2,28,NULL,'Así que el Hijo del hombre es Señor aun del sábado.','2026-2'),
('2026-07-15','Miércoles','El Sábado','Lucas 6:5','Lucas',6,5,NULL,'Y les decía: El Hijo del hombre es Señor aun del sábado.','2026-2'),
('2026-07-16','Jueves','El Sábado','Lucas 23:56','Lucas',23,56,NULL,'Y vueltas, aparejaron drogas aromáticas y ungüentos; y reposaron el sábado, conforme al mandamiento.','2026-2'),
('2026-07-17','Viernes','El Sábado','Hechos 13:42','Hechos',13,42,NULL,'Y saliendo ellos de la sinagoga de los Judíos, los Gentiles les rogaron que el sábado siguiente les hablasen estas palabras.','2026-2'),
('2026-07-18','Sábado','El Sábado','Hechos 13:44','Hechos',13,44,NULL,'Y el sábado siguiente se juntó casi toda la ciudad á oir la palabra de Dios.','2026-2'),
('2026-07-19','Domingo','La Buena Doctrina','Hechos 2:42','Hechos',2,42,NULL,'Y perseveraban en la doctrina de los apóstoles, y en la comunión, y en el partimiento del pan, y en las oraciones.','2026-2'),
('2026-07-20','Lunes','La Buena Doctrina','Romanos 6:17','Romanos',6,17,NULL,'Empero gracias á Dios, que aunque fuisteis siervos del pecado, habéis obedecido de corazón á aquella forma de doctrina á la cual sois entregados;','2026-2'),
('2026-07-21','Martes','La Buena Doctrina','Romanos 12:7','Romanos',12,7,NULL,'O si ministerio, en servir; ó el que enseña, en doctrina;','2026-2'),
('2026-07-22','Miércoles','La Buena Doctrina','Romanos 16:17','Romanos',16,17,NULL,'Y os ruego hermanos, que miréis los que causan disensiones y escándalos contra la doctrina que vosotros habéis aprendido; y apartaos de ellos.','2026-2'),
('2026-07-23','Jueves','La Buena Doctrina','2 Tesalonicenses 2:15','2 Tesalonicenses',2,15,NULL,'Así que, hermanos, estad firmes, y retened la doctrina que habéis aprendido, sea por palabra, ó por carta nuestra.','2026-2'),
('2026-07-24','Viernes','La Buena Doctrina','1 Timoteo 4:6','1 Timoteo',4,6,NULL,'Si esto propusieres á los hermanos, serás buen ministro de Jesucristo, criado en las palabras de la fe y de la buena doctrina, la cual has alcanzado.','2026-2'),
('2026-07-25','Sábado','La Buena Doctrina','Tito 2:1','Tito',2,1,NULL,'Empero tú, habla lo que conviene á la sana doctrina:','2026-2'),
('2026-07-26','Domingo','Honestidad','Romanos 13:13','Romanos',13,13,NULL,'Andemos como de día, honestamente: no en glotonerías y borracheras, no en lechos y disoluciones, no en pedencias y envidia:','2026-2'),
('2026-07-27','Lunes','Honestidad','2 Corintios 8:21','2 Corintios',8,21,NULL,'Procurando las cosas honestas, no sólo delante del Señor, mas aun delante de los hombres.','2026-2'),
('2026-07-28','Martes','Honestidad','1 Timoteo 3:11','1 Timoteo',3,11,NULL,'Las mujeres asimismo, honestas, no detractoras, templadas, fieles en todo.','2026-2'),
('2026-07-29','Miércoles','Honestidad','1 Timoteo 3:4','1 Timoteo',3,4,NULL,'Que gobierne bien su casa, que tenga sus hijos en sujeción con toda honestidad;','2026-2'),
('2026-07-30','Jueves','Honestidad','Filipenses 4:8','Filipenses',4,8,NULL,'Por lo demás, hermanos, todo lo que es verdadero, todo lo honesto, todo lo justo, todo lo puro, todo lo amable, todo lo que es de buen nombre; si hay virtud alguna, si alguna alabanza, en esto pensad.','2026-2'),
('2026-07-31','Viernes','Honestidad','1 Timoteo 2:9, 10','1 Timoteo',2,9,10,'Asimismo también las mujeres, ataviándose en hábito honesto, con vergüenza y modestia; no con cabellos encrespados, ú oro, ó perlas, ó vestidos costosos, Sino de buenas obras, como conviene á mujeres que profesan piedad.','2026-2'),
-- ===================== AGOSTO 2026 =====================
('2026-08-01','Sábado','Honestidad','1 Timoteo 3:8','1 Timoteo',3,8,NULL,'Los diáconos asimismo, deben ser honestos, no bilingües, no dados á mucho vino, no amadores de torpes ganancias;','2026-2'),
('2026-08-02','Domingo','Entendimiento','Proverbios 13:15','Proverbios',13,15,NULL,'El buen entendimiento conciliará gracia: mas el camino de los prevaricadores es duro.','2026-2'),
('2026-08-03','Lunes','Entendimiento','Proverbios 15:32','Proverbios',15,32,NULL,'El que tiene en poco la disciplina, menosprecia su alma: mas el que escucha la corrección, tiene entendimiento.','2026-2'),
('2026-08-04','Martes','Entendimiento','Romanos 12:2','Romanos',12,2,NULL,'Y no os conforméis á este siglo; mas reformaos por la renovación de vuestro entendimiento, para que experimentéis cuál sea la buena voluntad de Dios, agradable y perfecta.','2026-2'),
('2026-08-05','Miércoles','Entendimiento','1 Corintios 14:15','1 Corintios',14,15,NULL,'¿Qué pues? Oraré con el espíritu, mas oraré también con entendimiento; cantaré con el espíritu, mas cantaré también con entendimiento.','2026-2'),
('2026-08-06','Jueves','Entendimiento','Efesios 1:18','Efesios',1,18,NULL,'Alumbrando los ojos de vuestro entendimiento, para que sepáis cuál sea la esperanza de su vocación, y cuáles las riquezas de la gloria de su herencia en los santos,','2026-2'),
('2026-08-07','Viernes','Entendimiento','2 Pedro 3:1','2 Pedro',3,1,NULL,'Carísimos, yo os escribo ahora esta segunda carta, por las cuales ambas despierto con exhortación vuestro limpio entendimiento;','2026-2'),
('2026-08-08','Sábado','Entendimiento','1 Juan 5:20','1 Juan',5,20,NULL,'Empero sabemos que el Hijo de Dios es venido, y nos ha dado entendimiento para conocer al que es verdadero: y estamos en el verdadero, en su Hijo Jesucristo. Este es el verdadero Dios, y la vida eterna.','2026-2'),
('2026-08-09','Domingo','Firmeza','Hebreos 3:14','Hebreos',3,14,NULL,'Porque participantes de Cristo somos hechos, con tal que conservemos firme hasta el fin el principio de nuestra confianza;','2026-2'),
('2026-08-10','Lunes','Firmeza','Romanos 5:2','Romanos',5,2,NULL,'Por el cual también tenemos entrada por la fe á esta gracia en la cual estamos firmes, y nos gloriamos en la esperanza de la gloria de Dios.','2026-2'),
('2026-08-11','Martes','Firmeza','2 Pedro 1:10','2 Pedro',1,10,NULL,'Por lo cual, hermanos, procurad tanto más de hacer firme vuestra vocación y elección; porque haciendo estas cosas, no caeréis jamás.','2026-2'),
('2026-08-12','Miércoles','Firmeza','Romanos 15:1','Romanos',15,1,NULL,'Así que, los que somos más firmes debemos sobrellevar las flaquezas de los flacos, y no agradarnos á nosotros mismos.','2026-2'),
('2026-08-13','Jueves','Firmeza','1 Corintios 15:58','1 Corintios',15,58,NULL,'Así que, hermanos míos amados, estad firmes y constantes, creciendo en la obra del Señor siempre, sabiendo que vuestro trabajo en el Señor no es vano.','2026-2'),
('2026-08-14','Viernes','Firmeza','Efesios 6:11','Efesios',6,11,NULL,'Vestíos de toda la armadura de Dios, para que podáis estar firmes contra las asechanzas del diablo.','2026-2'),
('2026-08-15','Sábado','Firmeza','Filipenses 4:1','Filipenses',4,1,NULL,'Así que, hermanos míos amados y deseados, gozo y corona mía, estad así firmes en el Señor, amados.','2026-2'),
('2026-08-16','Domingo','Fruto','Lucas 6:44','Lucas',6,44,NULL,'Porque cada árbol por su fruto es conocido: que no cogen higos de los espinos, ni vendimian uvas de las zarzas.','2026-2'),
('2026-08-17','Lunes','Fruto','Lucas 8:15','Lucas',8,15,NULL,'Mas la que en buena tierra, éstos son los que con corazón bueno y recto retienen la palabra oída, y llevan fruto en paciencia.','2026-2'),
('2026-08-18','Martes','Fruto','Juan 12:24','Juan',12,24,NULL,'De cierto, de cierto os digo, que si el grano de trigo no cae en la tierra y muere, él solo queda; mas si muriere, mucho fruto lleva.','2026-2'),
('2026-08-19','Miércoles','Fruto','Romanos 6:22','Romanos',6,22,NULL,'Mas ahora, librados del pecado, y hechos siervos á Dios, tenéis por vuestro fruto la santificación, y por fin la vida eterna.','2026-2'),
('2026-08-20','Jueves','Fruto','Gálatas 5:22','Gálatas',5,22,NULL,'Mas el fruto del Espíritu es: caridad, gozo, paz, tolerancia, benignidad, bondad, fe,','2026-2'),
('2026-08-21','Viernes','Fruto','Efesios 5:9','Efesios',5,9,NULL,'(Porque el fruto del Espíritu es en toda bondad, y justicia, y verdad;)','2026-2'),
('2026-08-22','Sábado','Fruto','Santiago 3:18','Santiago',3,18,NULL,'Y el fruto de justicia se siembra en paz para aquellos que hacen paz.','2026-2'),
('2026-08-23','Domingo','Hermanos En Cristo','Mateo 12:48','Mateo',12,48,NULL,'Y respondiendo él al que le decía esto, dijo: ¿Quién es mi madre y quiénes son mis hermanos?','2026-2'),
('2026-08-24','Lunes','Hermanos En Cristo','Mateo 12:49','Mateo',12,49,NULL,'Y extendiendo su mano hacia sus discípulos, dijo: He aquí mi madre y mis hermanos.','2026-2'),
('2026-08-25','Martes','Hermanos En Cristo','Mateo 12:50','Mateo',12,50,NULL,'Porque todo aquel que hiciere la voluntad de mi Padre que está en los cielos, ese es mi hermano, y hermana, y madre.','2026-2'),
('2026-08-26','Miércoles','Hermanos En Cristo','Marcos 3:33','Marcos',3,33,NULL,'Y él les respondió, diciendo: ¿Quién es mi madre y mis hermanos?','2026-2'),
('2026-08-27','Jueves','Hermanos En Cristo','Marcos 3:34','Marcos',3,34,NULL,'Y mirando á los que estaban sentados alrededor de él, dijo: He aquí mi madre y hermanos.','2026-2'),
('2026-08-28','Viernes','Hermanos En Cristo','Marcos 3:35','Marcos',3,35,NULL,'Porque cualquiera que hiciere la voluntad de Dios, éste es mi hermano, y mi hermana, y mi madre.','2026-2'),
('2026-08-29','Sábado','Hermanos En Cristo','Lucas 8:21','Lucas',8,21,NULL,'El entonces respondiendo, les dijo: Mi madre y mis hermanos son los que oyen la palabra de Dios, y la ejecutan.','2026-2'),
('2026-08-30','Domingo','Mandamientos De Dios','Proverbios 7:1','Proverbios',7,1,NULL,'Hijo mío, guarda mis razones, y encierra contigo mis mandamientos.','2026-2'),
('2026-08-31','Lunes','Mandamientos De Dios','Proverbios 7:2','Proverbios',7,2,NULL,'Guarda mis mandamientos, y vivirás; y mi ley como las niñas de tus ojos.','2026-2'),
-- ===================== SEPTIEMBRE 2026 =====================
('2026-09-01','Martes','Mandamientos De Dios','Eclesiastés 12:13','Eclesiastés',12,13,NULL,'El fin de todo el discurso oído es este: Teme á Dios, y guarda sus mandamientos; porque esto es el todo del hombre.','2026-2'),
('2026-09-02','Miércoles','Mandamientos De Dios','Mateo 5:19','Mateo',5,19,NULL,'De manera que cualquiera que infringiere uno de estos mandamientos muy pequeños, y así enseñare á los hombres, muy pequeño será llamado en el reino de los cielos: mas cualquiera que hiciere y enseñare, éste será llamado grande en el reino de los cielos.','2026-2'),
('2026-09-03','Jueves','Mandamientos De Dios','1 Juan 5:2','1 Juan',5,2,NULL,'En esto conocemos que amamos á los hijos de Dios, cuando amamos á Dios, y guardamos sus mandamientos.','2026-2'),
('2026-09-04','Viernes','Mandamientos De Dios','Apocalipsis 14:12','Apocalipsis',14,12,NULL,'Aquí está la paciencia de los santos; aquí están los que guardan los mandamientos de Dios, y la fe de Jesús.','2026-2'),
('2026-09-05','Sábado','Mandamientos De Dios','1 Juan 2:4','1 Juan',2,4,NULL,'El que dice, Yo le he conocido, y no guarda sus mandamientos, el tal es mentiroso, y no hay verdad en él;','2026-2'),
('2026-09-06','Domingo','Paciencia','Romanos 5:3','Romanos',5,3,NULL,'Y no sólo esto, mas aun nos gloriamos en las tribulaciones, sabiendo que la tribulación produce paciencia;','2026-2'),
('2026-09-07','Lunes','Paciencia','2 Corintios 6:4','2 Corintios',6,4,NULL,'Antes habiéndonos en todas cosas como ministros de Dios, en mucha paciencia, en tribulaciones, en necesidades, en angustias;','2026-2'),
('2026-09-08','Martes','Paciencia','Efesios 4:2','Efesios',4,2,NULL,'Con toda humildad y mansedumbre, con paciencia soportando los unos á los otros en amor;','2026-2'),
('2026-09-09','Miércoles','Paciencia','1 Timoteo 6:11','1 Timoteo',6,11,NULL,'Mas tú, oh hombre de Dios, huye de estas cosas, y sigue la justicia, la piedad, la fe, la caridad, la paciencia, la mansedumbre.','2026-2'),
('2026-09-10','Jueves','Paciencia','Hebreos 6:12','Hebreos',6,12,NULL,'Que no os hagáis perezosos, mas imitadores de aquellos que por la fe y la paciencia heredan las promesas.','2026-2'),
('2026-09-11','Viernes','Paciencia','Santiago 5:7','Santiago',5,7,NULL,'Pues, hermanos, tened paciencia hasta la venida del Señor. Mirad cómo el labrador espera el precioso fruto de la tierra, aguardando con paciencia, hasta que reciba la lluvia temprana y tardía.','2026-2'),
('2026-09-12','Sábado','Paciencia','Apocalipsis 14:12','Apocalipsis',14,12,NULL,'Aquí está la paciencia de los santos; aquí están los que guardan los mandamientos de Dios, y la fe de Jesús.','2026-2'),
('2026-09-13','Domingo','El Nuevo Nacimiento','Juan 3:5','Juan',3,5,NULL,'Respondió Jesús: De cierto, de cierto te digo, que el que no naciere de agua y del Espíritu, no puede entrar en el reino de Dios.','2026-2'),
('2026-09-14','Lunes','El Nuevo Nacimiento','1 Juan 4:7','1 Juan',4,7,NULL,'Carísimos, amémonos unos á otros; porque el amor es de Dios. Cualquiera que ama, es nacido de Dios, y conoce á Dios.','2026-2'),
('2026-09-15','Martes','El Nuevo Nacimiento','1 Juan 5:1','1 Juan',5,1,NULL,'Todo aquel que cree que Jesús es el Cristo, es nacido de Dios: y cualquiera que ama al que ha engendrado, ama también al que es nacido de él.','2026-2'),
('2026-09-16','Miércoles','El Nuevo Nacimiento','1 Pedro 1:23','1 Pedro',1,23,NULL,'Siendo renacidos, no de simiente corruptible, sino de incorruptible, por la palabra de Dios, que vive y permanece para siempre.','2026-2'),
('2026-09-17','Jueves','El Nuevo Nacimiento','1 Juan 5:4','1 Juan',5,4,NULL,'Porque todo aquello que es nacido de Dios vence al mundo: y esta es la victoria que vence al mundo, nuestra fe.','2026-2'),
('2026-09-18','Viernes','El Nuevo Nacimiento','Romanos 12:2','Romanos',12,2,NULL,'Y no os conforméis á este siglo; mas reformaos por la renovación de vuestro entendimiento, para que experimentéis cuál sea la buena voluntad de Dios, agradable y perfecta.','2026-2'),
('2026-09-19','Sábado','El Nuevo Nacimiento','1 Juan 2:29','1 Juan',2,29,NULL,'Si sabéis que él es justo, sabed también que cualquiera que hace justicia, es nacido de él.','2026-2'),
('2026-09-20','Domingo','Limpiando El Templo Del Corazon','Juan 2:16','Juan',2,16,NULL,'Y á los que vendían las palomas, dijo: Quitad de aquí esto, y no hagáis la casa de mi Padre casa de mercado.','2026-2'),
('2026-09-21','Lunes','Limpiando El Templo Del Corazon','Proverbios 20:9','Proverbios',20,9,NULL,'¿Quién podrá decir: Yo he limpiado mi corazón, limpio estoy de mi pecado?','2026-2'),
('2026-09-22','Martes','Limpiando El Templo Del Corazon','Proverbios 16:6','Proverbios',16,6,NULL,'Con misericordia y verdad se corrige el pecado: y con el temor de Jehová se apartan del mal los hombres.','2026-2'),
('2026-09-23','Miércoles','Limpiando El Templo Del Corazon','1 Juan 1:9','1 Juan',1,9,NULL,'Si confesamos nuestros pecados, él es fiel y justo para que nos perdone nuestros pecados, y nos limpie de toda maldad.','2026-2'),
('2026-09-24','Jueves','Limpiando El Templo Del Corazon','Salmos 51:2','Salmos',51,2,NULL,'Lávame más y más de mi maldad, y límpiame de mi pecado.','2026-2'),
('2026-09-25','Viernes','Limpiando El Templo Del Corazon','Salmos 79:9','Salmos',79,9,NULL,'Ayúdanos, oh Dios, salud nuestra, por la gloria de tu nombre: y líbranos, y aplácate sobre nuestros pecados por amor de tu nombre.','2026-2'),
('2026-09-26','Sábado','Limpiando El Templo Del Corazon','1 Corintios 6:11','1 Corintios',6,11,NULL,'Y esto erais algunos: mas ya sois lavados, mas ya sois santificados, mas ya sois justificados en el nombre del Señor Jesús, y por el Espíritu de nuestro Dios.','2026-2'),
('2026-09-27','Domingo','El Pan De La Vida','Juan 6:26','Juan',6,26,NULL,'Respondióles Jesús, y dijo: De cierto, de cierto os digo, que me buscáis, no porque habéis visto las señales, sino porque comisteis el pan y os hartasteis.','2026-2'),
('2026-09-28','Lunes','El Pan De La Vida','Juan 6:27','Juan',6,27,NULL,'Trabajad no por la comida que perece, mas por la comida que á vida eterna permanece, la cual el Hijo del hombre os dará: porque á éste señaló el Padre, que es Dios.','2026-2'),
('2026-09-29','Martes','El Pan De La Vida','Juan 6:35','Juan',6,35,NULL,'Y Jesús les dijo: Yo soy el pan de vida: el que á mí viene, nunca tendrá hambre; y el que en mí cree, no tendrá sed jamás.','2026-2'),
('2026-09-30','Miércoles','El Pan De La Vida','Juan 6:51','Juan',6,51,NULL,'Yo soy el pan vivo que he descendido del cielo: si alguno comiere de este pan, vivirá para siempre; y el pan que yo daré es mi carne, la cual yo daré por la vida del mundo.','2026-2'),
-- ===================== OCTUBRE 2026 =====================
('2026-10-01','Jueves','El Pan De La Vida','Juan 6:57','Juan',6,57,NULL,'Como me envió el Padre viviente, y yo vivo por el Padre, asimismo el que me come, él también vivirá por mí.','2026-2'),
('2026-10-02','Viernes','El Pan De La Vida','Juan 6:54','Juan',6,54,NULL,'El que come mi carne y bebe mi sangre, tiene vida eterna: y yo le resucitaré en el día postrero.','2026-2'),
('2026-10-03','Sábado','El Pan De La Vida','Juan 6:63','Juan',6,63,NULL,'El espíritu es el que da vida; la carne nada aprovecha: las palabras que yo os he hablado, son espíritu, y son vida.','2026-2'),
('2026-10-04','Domingo','La Luz De La Vida','Juan 8:12','Juan',8,12,NULL,'Y hablóles Jesús otra vez, diciendo: Yo soy la luz del mundo: el que me sigue, no andará en tinieblas, mas tendrá la lumbre de la vida.','2026-2'),
('2026-10-05','Lunes','La Luz De La Vida','Juan 1:4','Juan',1,4,NULL,'En él estaba la vida, y la vida era la luz de los hombres.','2026-2'),
('2026-10-06','Martes','La Luz De La Vida','Juan 1:9','Juan',1,9,NULL,'Aquél era la luz verdadera, que alumbra á todo hombre que viene á este mundo.','2026-2'),
('2026-10-07','Miércoles','La Luz De La Vida','Juan 3:19','Juan',3,19,NULL,'Y esta es la condenación: porque la luz vino al mundo, y los hombres amaron más las tinieblas que la luz; porque sus obras eran malas.','2026-2'),
('2026-10-08','Jueves','La Luz De La Vida','Juan 9:5','Juan',9,5,NULL,'Entre tanto que estuviere en el mundo, luz soy del mundo.','2026-2'),
('2026-10-09','Viernes','La Luz De La Vida','Juan 12:35','Juan',12,35,NULL,'Entonces Jesús les dice: Aun por un poco estará la luz entre vosotros: andad entre tanto que tenéis luz, porque no os sorprendan las tinieblas; porque el que anda en tinieblas, no sabe dónde va.','2026-2'),
('2026-10-10','Sábado','La Luz De La Vida','Juan 12:46','Juan',12,46,NULL,'Yo la luz he venido al mundo, para que todo aquel que cree en mí no permanezca en tinieblas.','2026-2'),
('2026-10-11','Domingo','Victoria Sobre La Muerte','Juan 11:25','Juan',11,25,NULL,'Dícele Jesús: Yo soy la resurrección y la vida: el que cree en mí, aunque esté muerto, vivirá.','2026-2'),
('2026-10-12','Lunes','Victoria Sobre La Muerte','Juan 10:17','Juan',10,17,NULL,'Por eso me ama el Padre, porque yo pongo mi vida, para volverla á tomar.','2026-2'),
('2026-10-13','Martes','Victoria Sobre La Muerte','2 Timoteo 1:10','2 Timoteo',1,10,NULL,'Mas ahora es manifestada por la aparición de nuestro Salvador Jesucristo, el cual quitó la muerte, y sacó á la luz la vida y la inmortalidad por el evangelio;','2026-2'),
('2026-10-14','Miércoles','Victoria Sobre La Muerte','Juan 5:21','Juan',5,21,NULL,'Porque como el Padre levanta los muertos, y les da vida, así también el Hijo á los que quiere da vida.','2026-2'),
('2026-10-15','Jueves','Victoria Sobre La Muerte','Juan 6:40','Juan',6,40,NULL,'Y esta es la voluntad del que me ha enviado: Que todo aquel que ve al Hijo, y cree en él, tenga vida eterna: y yo le resucitaré en el día postrero.','2026-2'),
('2026-10-16','Viernes','Victoria Sobre La Muerte','1 Corintios 15:54','1 Corintios',15,54,NULL,'Y cuando esto corruptible fuere vestido de incorrupción, y esto mortal fuere vestido de inmortalidad, entonces se efectuará la palabra que está escrita: Sorbida es la muerte con victoria.','2026-2'),
('2026-10-17','Sábado','Victoria Sobre La Muerte','Romanos 8:11','Romanos',8,11,NULL,'Y si el Espíritu de aquel que levantó de los muertos á Jesús mora en vosotros, el que levantó á Cristo Jesús de los muertos, vivificará también vuestros cuerpos mortales por su Espíritu que mora en vosotros.','2026-2'),
('2026-10-18','Domingo','Peligros De Hipocresia','Mateo 23:13','Mateo',23,13,NULL,'Mas ¡ay de vosotros, escribas y Fariseos, hipócritas! porque cerráis el reino de los cielos delante de los hombres; que ni vosotros entráis, ni á los que están entrando dejáis entrar.','2026-2'),
('2026-10-19','Lunes','Peligros De Hipocresia','Mateo 23:14','Mateo',23,14,NULL,'¡Ay de vosotros, escribas y Fariseos, hipócritas! porque coméis las casas de las viudas, y por pretexto hacéis larga oración: por esto llevaréis más grave juicio.','2026-2'),
('2026-10-20','Martes','Peligros De Hipocresia','Mateo 23:15','Mateo',23,15,NULL,'¡Ay de vosotros, escribas y Fariseos, hipócritas! porque rodeáis la mar y la tierra por hacer un prosélito; y cuando fuere hecho, le hacéis hijo del infierno doble más que vosotros.','2026-2'),
('2026-10-21','Miércoles','Peligros De Hipocresia','Mateo 23:23','Mateo',23,23,NULL,'¡Ay de vosotros, escribas y Fariseos, hipócritas! porque diezmáis la menta y el eneldo y el comino, y dejasteis lo que es lo más grave de la ley, es á saber, el juicio y la misericordia y la fe: esto era menester hacer, y no dejar lo otro.','2026-2'),
('2026-10-22','Jueves','Peligros De Hipocresia','Mateo 23:25','Mateo',23,25,NULL,'¡Ay de vosotros, escribas y Fariseos, hipócritas! porque limpiáis lo que está de fuera del vaso y del plato; mas de dentro están llenos de robo y de injusticia.','2026-2'),
('2026-10-23','Viernes','Peligros De Hipocresia','Mateo 23:27','Mateo',23,27,NULL,'¡Ay de vosotros, escribas y Fariseos, hipócritas! porque sois semejantes á sepulcros blanqueados, que de fuera, á la verdad, se muestran hermosos, mas de dentro están llenos de huesos de muertos y de toda suciedad.','2026-2'),
('2026-10-24','Sábado','Peligros De Hipocresia','Lucas 16:15','Lucas',16,15,NULL,'Y díjoles: Vosotros sois los que os justificáis á vosotros mismos delante de los hombres; mas Dios conoce vuestros corazones; porque lo que los hombres tienen por sublime, delante de Dios es abominación.','2026-2'),
('2026-10-25','Domingo','El Evangelio Al Mundo','Marcos 13:10','Marcos',13,10,NULL,'Y á todas las gentes conviene que el evangelio sea predicado antes.','2026-2'),
('2026-10-26','Lunes','El Evangelio Al Mundo','Mateo 24:14','Mateo',24,14,NULL,'Y será predicado este evangelio del reino en todo el mundo, por testimonio á todos los Gentiles; y entonces vendrá el fin.','2026-2'),
('2026-10-27','Martes','El Evangelio Al Mundo','Juan 20:21','Juan',20,21,NULL,'Entonces les dijo Jesús otra vez: Paz á vosotros; como me envió el Padre, así también yo os envío.','2026-2'),
('2026-10-28','Miércoles','El Evangelio Al Mundo','Lucas 24:46, 47','Lucas',24,46,47,'Y díjoles: Así está escrito, y así fué necesario que el Cristo padeciese, y resucitase de los muertos al tercer día; Y que se predicase en su nombre el arrepentimiento y la remisión de pecados en todas las naciones, comenzando de Jerusalem.','2026-2'),
('2026-10-29','Jueves','El Evangelio Al Mundo','Juan 21:17','Juan',21,17,NULL,'Dícele la tercera vez: Simón, hijo de Jonás, ¿me amas? Entristecióse Pedro de que le dijese la tercera vez: ¿Me amas? y dícele: Señor, tú sabes todas las cosas; tú sabes que te amo. Dícele Jesús: Apacienta mis ovejas.','2026-2'),
('2026-10-30','Viernes','El Evangelio Al Mundo','Mateo 28:19','Mateo',28,19,NULL,'Por tanto, id, y doctrinad á todos los Gentiles, bautizándolos en el nombre del Padre, y del Hijo, y del Espíritu Santo:','2026-2'),
('2026-10-31','Sábado','El Evangelio Al Mundo','Hechos 1:8','Hechos',1,8,NULL,'Mas recibiréis la virtud del Espíritu Santo que vendrá sobre vosotros; y me sereís testigos en Jerusalem, y en toda Judea, y Samaria, y hasta lo último de la tierra.','2026-2'),
-- ===================== NOVIEMBRE 2026 =====================
('2026-11-01','Domingo','El Amor De Dios Por Nosotros','Juan 3:16','Juan',3,16,NULL,'Porque de tal manera amó Dios al mundo, que ha dado á su Hijo unigénito, para que todo aquel que en él cree, no se pierda, mas tenga vida eterna.','2026-2'),
('2026-11-02','Lunes','El Amor De Dios Por Nosotros','Romanos 5:8','Romanos',5,8,NULL,'Mas Dios encarece su caridad para con nosotros, porque siendo aún pecadores, Cristo murió por nosotros.','2026-2'),
('2026-11-03','Martes','El Amor De Dios Por Nosotros','Romanos 8:32','Romanos',8,32,NULL,'El que aun á su propio Hijo no perdonó, antes le entregó por todos nosotros, ¿cómo no nos dará también con él todas las cosas?','2026-2'),
('2026-11-04','Miércoles','El Amor De Dios Por Nosotros','Romanos 8:38, 39','Romanos',8,38,39,'Por lo cual estoy cierto que ni la muerte, ni la vida, ni ángeles, ni principados, ni potestades, ni lo presente, ni lo por venir, Ni lo alto, ni lo bajo, ni ninguna criatura nos podrá apartar del amor de Dios, que es en Cristo Jesús Señor nuestro.','2026-2'),
('2026-11-05','Jueves','El Amor De Dios Por Nosotros','1 Juan 3:1','1 Juan',3,1,NULL,'Mirad cuál amor nos ha dado el Padre, que seamos llamados hijos de Dios: por esto el mundo no nos conoce, porque no le conoce á él.','2026-2'),
('2026-11-06','Viernes','El Amor De Dios Por Nosotros','1 Juan 4:9','1 Juan',4,9,NULL,'En esto se mostró el amor de Dios para con nosotros, en que Dios envió á su Hijo unigénito al mundo, para que vivamos por él.','2026-2'),
('2026-11-07','Sábado','El Amor De Dios Por Nosotros','1 Juan 4:10','1 Juan',4,10,NULL,'En esto consiste el amor: no que nosotros hayamos amado á Dios, sino que él nos amó á nosotros, y ha enviado á su Hijo en propiciación por nuestros pecados.','2026-2'),
('2026-11-08','Domingo','Por Qué Vino Cristo','Juan 10:9','Juan',10,9,NULL,'Yo soy la puerta: el que por mí entrare, será salvo; y entrará, y saldrá, y hallará pastos.','2026-2'),
('2026-11-09','Lunes','Por Qué Vino Cristo','Hechos 26:23','Hechos',26,23,NULL,'Que Cristo había de padecer, y ser el primero de la resurrección de los muertos, para anunciar luz al pueblo y á los Gentiles.','2026-2'),
('2026-11-10','Martes','Por Qué Vino Cristo','Mateo 18:11','Mateo',18,11,NULL,'Porque el Hijo del hombre ha venido para salvar lo que se había perdido.','2026-2'),
('2026-11-11','Miércoles','Por Qué Vino Cristo','Mateo 9:13','Mateo',9,13,NULL,'Andad pues, y aprended qué cosa es: Misericordia quiero, y no sacrificio: porque no he venido á llamar justos, sino pecadores á arrepentimiento.','2026-2'),
('2026-11-12','Jueves','Por Qué Vino Cristo','Marcos 10:45','Marcos',10,45,NULL,'Porque el Hijo del hombre tampoco vino para ser servido, mas para servir, y dar su vida en rescate por muchos.','2026-2'),
('2026-11-13','Viernes','Por Qué Vino Cristo','Lucas 19:10','Lucas',19,10,NULL,'Porque el Hijo del hombre vino á buscar y á salvar lo que se había perdido.','2026-2'),
('2026-11-14','Sábado','Por Qué Vino Cristo','Juan 10:10','Juan',10,10,NULL,'El ladrón no viene sino para hurtar, y matar, y destruir: yo he venido para que tengan vida, y para que la tengan en abundancia.','2026-2'),
('2026-11-15','Domingo','Él, Nuestro Salvador','Mateo 1:21','Mateo',1,21,NULL,'Y parirá un hijo, y llamarás su nombre JESUS, porque él salvará á su pueblo de sus pecados.','2026-2'),
('2026-11-16','Lunes','Él, Nuestro Salvador','Hechos 4:12','Hechos',4,12,NULL,'Y en ningún otro hay salud; porque no hay otro nombre debajo del cielo, dado á los hombres, en que podamos ser salvos.','2026-2'),
('2026-11-17','Martes','Él, Nuestro Salvador','Hechos 13:38','Hechos',13,38,NULL,'Séaos pues notorio, varones hermanos, que por éste os es anunciada remisión de pecados;','2026-2'),
('2026-11-18','Miércoles','Él, Nuestro Salvador','Hechos 13:39','Hechos',13,39,NULL,'Y de todo lo que por la ley de Moisés no pudisteis ser justificados, en éste es justificado todo aquel que creyere.','2026-2'),
('2026-11-19','Jueves','Él, Nuestro Salvador','Romanos 5:10','Romanos',5,10,NULL,'Porque si siendo enemigos, fuimos reconciliados con Dios por la muerte de su Hijo, mucho más, estando reconciliados, seremos salvos por su vida.','2026-2'),
('2026-11-20','Viernes','Él, Nuestro Salvador','Colosenses 1:14','Colosenses',1,14,NULL,'En el cual tenemos redención por su sangre, la remisión de pecados:','2026-2'),
('2026-11-21','Sábado','Él, Nuestro Salvador','1 Timoteo 1:15','1 Timoteo',1,15,NULL,'Palabra fiel y digna de ser recibida de todos: que Cristo Jesús vino al mundo para salvar á los pecadores, de los cuales yo soy el primero.','2026-2'),
('2026-11-22','Domingo','Nuestro Sustituto','Romanos 4:25','Romanos',4,25,NULL,'El cual fué entregado por nuestros delitos, y resucitado para nuestra justificación.','2026-2'),
('2026-11-23','Lunes','Nuestro Sustituto','Gálatas 1:4','Gálatas',1,4,NULL,'El cual se dió á sí mismo por nuestros pecados para librarnos de este presente siglo malo, conforme á la voluntad de Dios y Padre nuestro;','2026-2'),
('2026-11-24','Martes','Nuestro Sustituto','Gálatas 3:13','Gálatas',3,13,NULL,'Cristo nos redimió de la maldición de la ley, hecho por nosotros maldición; (porque está escrito: Maldito cualquiera que es colgado en madero:)','2026-2'),
('2026-11-25','Miércoles','Nuestro Sustituto','Efesios 5:2','Efesios',5,2,NULL,'Y andad en amor, como también Cristo nos amó, y se entregó á sí mismo por nosotros, ofrenda y sacrificio á Dios en olor suave.','2026-2'),
('2026-11-26','Jueves','Nuestro Sustituto','1 Pedro 2:24','1 Pedro',2,24,NULL,'El cual mismo llevó nuestros pecados en su cuerpo sobre el madero, para que nosotros siendo muertos á los pecados, vivamos á la justicia: por la herida del cual habéis sido sanados.','2026-2'),
('2026-11-27','Viernes','Nuestro Sustituto','1 Pedro 3:18','1 Pedro',3,18,NULL,'Porque también Cristo padeció una vez por los pecados, el justo por los injustos, para llevarnos á Dios, siendo á la verdad muerto en la carne, pero vivificado en espíritu;','2026-2'),
('2026-11-28','Sábado','Nuestro Sustituto','Apocalipsis 5:9','Apocalipsis',5,9,NULL,'Y cantaban un nuevo cántico, diciendo: Digno eres de tomar el libro, y de abrir sus sellos; porque tú fuiste inmolado, y nos has redimido para Dios con tu sangre, de todo linaje y lengua y pueblo y nación;','2026-2'),
('2026-11-29','Domingo','El Bautismo','Mateo 3:16, 17','Mateo',3,16,17,'Y Jesús, después que fué bautizado, subió luego del agua; y he aquí los cielos le fueron abiertos, y vió al Espíritu de Dios que descendía como paloma, y venía sobre él. Y he aquí una voz de los cielos que decía: Este es mi Hijo amado, en el cual tengo contentamiento.','2026-2'),
('2026-11-30','Lunes','El Bautismo','Romanos 6:3, 4','Romanos',6,3,4,'¿O no sabéis que todos los que somos bautizados en Cristo Jesús, somos bautizados en su muerte? Porque somos sepultados juntamente con él á muerte por el bautismo; para que como Cristo resucitó de los muertos por la gloria del Padre, así también nosotros andemos en novedad de vida.','2026-2'),
-- ===================== DICIEMBRE 2026 =====================
('2026-12-01','Martes','El Bautismo','1 Corintios 12:13','1 Corintios',12,13,NULL,'Porque por un Espíritu somos todos bautizados en un cuerpo, ora Judíos ó Griegos, ora siervos ó libres; y todos hemos bebido de un mismo Espíritu.','2026-2'),
('2026-12-02','Miércoles','El Bautismo','Tito 3:5','Tito',3,5,NULL,'No por obras de justicia que nosotros habíamos hecho, mas por su misericordia nos salvó, por el lavacro de la regeneración, y de la renovación del Espíritu Santo;','2026-2'),
('2026-12-03','Jueves','El Bautismo','Hechos 22:16','Hechos',22,16,NULL,'Ahora pues, ¿por qué te detienes? Levántate, y bautízate, y lava tus pecados, invocando su nombre.','2026-2'),
('2026-12-04','Viernes','El Bautismo','Efesios 4:5','Efesios',4,5,NULL,'Un Señor, una fe, un bautismo,','2026-2'),
('2026-12-05','Sábado','El Bautismo','Colosenses 2:12','Colosenses',2,12,NULL,'Sepultados juntamente con él en el bautismo, en el cual también resucitasteis con él, por la fe de la operación de Dios que le levantó de los muertos.','2026-2'),
('2026-12-06','Domingo','Dadivosidad Voluntaria','2 Corintios 9:7','2 Corintios',9,7,NULL,'Cada uno dé como propuso en su corazón: no con tristeza, ó por necesidad; porque Dios ama el dador alegre.','2026-2'),
('2026-12-07','Lunes','Dadivosidad Voluntaria','1 Timoteo 6:18','1 Timoteo',6,18,NULL,'Que hagan bien, que sean ricos en buenas obras, dadivosos, que con facilidad comuniquen;','2026-2'),
('2026-12-08','Martes','Dadivosidad Voluntaria','2 Corintios 8:3','2 Corintios',8,3,NULL,'Pues de su grado han dado conforme á sus fuerzas, yo testifico, y aun sobre sus fuerzas;','2026-2'),
('2026-12-09','Miércoles','Dadivosidad Voluntaria','2 Corintios 8:12','2 Corintios',8,12,NULL,'Porque si primero hay la voluntad pronta, será acepta por lo que tiene, no por lo que no tiene.','2026-2'),
('2026-12-10','Jueves','Dadivosidad Voluntaria','Efesios 4:28','Efesios',4,28,NULL,'El que hurtaba, no hurte más; antes trabaje, obrando con sus manos lo que es bueno, para que tenga de qué dar al que padeciere necesidad.','2026-2'),
('2026-12-11','Viernes','Dadivosidad Voluntaria','Proverbios 11:25','Proverbios',11,25,NULL,'El alma liberal será engordada: y el que saciare, él también será saciado.','2026-2'),
('2026-12-12','Sábado','Dadivosidad Voluntaria','Lucas 6:38','Lucas',6,38,NULL,'Dad, y se os dará; medida buena, apretada, remecida, y rebosando darán en vuestro seno: porque con la misma medida que midiereis, os será vuelto á medir.','2026-2'),
('2026-12-13','Domingo','La Unidad','Juan 17:21','Juan',17,21,NULL,'Para que todos sean una cosa; como tú, oh Padre, en mí, y yo en ti, que también ellos sean en nosotros una cosa: para que el mundo crea que tú me enviaste.','2026-2'),
('2026-12-14','Lunes','La Unidad','Juan 17:23','Juan',17,23,NULL,'Yo en ellos, y tú en mí, para que sean consumadamente una cosa; que el mundo conozca que tú me enviaste, y que los has amado, como también á mí me has amado.','2026-2'),
('2026-12-15','Martes','La Unidad','1 Corintios 1:10','1 Corintios',1,10,NULL,'Os ruego pues, hermanos, por el nombre de nuestro Señor Jesucristo, que habléis todos una misma cosa, y que no haya entre vosotros disensiones, antes seáis perfectamente unidos en una misma mente y en un mismo parecer.','2026-2'),
('2026-12-16','Miércoles','La Unidad','Efesios 4:13','Efesios',4,13,NULL,'Hasta que todos lleguemos á la unidad de la fe y del conocimiento del Hijo de Dios, á un varón perfecto, á la medida de la edad de la plenitud de Cristo:','2026-2'),
('2026-12-17','Jueves','La Unidad','1 Pedro 3:8','1 Pedro',3,8,NULL,'Y finalmente, sed todos de un mismo corazón, compasivos, amándoos fraternalmente, misericordiosos, amigables;','2026-2'),
('2026-12-18','Viernes','La Unidad','Salmos 133:1','Salmos',133,1,NULL,'¡Mirad cuán bueno y cuán delicioso es habitar los hermanos igualmente en uno!','2026-2'),
('2026-12-19','Sábado','La Unidad','2 Corintios 13:11','2 Corintios',13,11,NULL,'Resta, hermanos, que tengáis gozo, seáis perfectos, tengáis consolación, sintáis una misma cosa, tengáis paz; y el Dios de paz y de caridad será con vosotros.','2026-2'),
('2026-12-20','Domingo','Nacimiento E Infancia De Cristo','Lucas 2:7','Lucas',2,7,NULL,'Y parió á su hijo primogénito, y le envolvió en pañales, y acostóle en un pesebre, porque no había lugar para ellos en el mesón.','2026-2'),
('2026-12-21','Lunes','Nacimiento E Infancia De Cristo','Lucas 2:10','Lucas',2,10,NULL,'Mas el ángel les dijo: No temáis; porque he aquí os doy nuevas de gran gozo, que será para todo el pueblo:','2026-2'),
('2026-12-22','Martes','Nacimiento E Infancia De Cristo','Lucas 2:11','Lucas',2,11,NULL,'Que os ha nacido hoy, en la ciudad de David, un Salvador, que es CRISTO el Señor.','2026-2'),
('2026-12-23','Miércoles','Nacimiento E Infancia De Cristo','Lucas 2:14','Lucas',2,14,NULL,'Gloria en las alturas á Dios, y en la tierra paz, buena voluntad para con los hombres.','2026-2'),
('2026-12-24','Jueves','Nacimiento E Infancia De Cristo','Lucas 2:29-32','Lucas',2,29,32,'Ahora despides, Señor, á tu siervo, conforme á tu palabra, en paz; Porque han visto mis ojos tu salvación, La cual has aparejado en presencia de todos los pueblos; Luz para ser revelada á los Gentiles, y la gloria de tu pueblo Israel.','2026-2'),
('2026-12-25','Viernes','Nacimiento E Infancia De Cristo','Lucas 2:34','Lucas',2,34,NULL,'Y los bendijo Simeón, y dijo á su madre María: He aquí, éste es puesto para caída y para levantamiento de muchos en Israel; y para señal á la que será contradicho;','2026-2'),
('2026-12-26','Sábado','Nacimiento E Infancia De Cristo','Mateo 2:11','Mateo',2,11,NULL,'Y entrando en la casa, vieron al niño con su madre María, y postrándose, le adoraron; y abriendo sus tesoros, le ofrecieron dones, oro é incienso y mirra.','2026-2'),
('2026-12-27','Domingo','Año Nuevo','Salmos 90:4','Salmos',90,4,NULL,'Porque mil años delante de tus ojos, son como el día de ayer, que pasó, y como una de las vigilias de la noche.','2026-2'),
('2026-12-28','Lunes','Año Nuevo','Salmos 90:9','Salmos',90,9,NULL,'Porque todos nuestros días declinan á causa de tu ira; acabamos nuestros años como un pensamiento.','2026-2'),
('2026-12-29','Martes','Año Nuevo','Salmos 90:10','Salmos',90,10,NULL,'Los días de nuestra edad son setenta años; que si en los más robustos son ochenta años, con todo su fortaleza es molestia y trabajo; porque es cortado presto, y volamos.','2026-2'),
('2026-12-30','Miércoles','Año Nuevo','Proverbios 3:1, 2','Proverbios',3,1,2,'Hijo mío, no te olvides de mi ley; y tu corazón guarde mis mandamientos: Porque largura de días, y años de vida y paz te aumentarán.','2026-2'),
('2026-12-31','Jueves','Año Nuevo','Proverbios 9:10, 11','Proverbios',9,10,11,'El temor de Jehová es el principio de la sabiduría; y la ciencia de los santos es inteligencia. Porque por mí se aumentarán tus días, y años de vida se te añadirán.','2026-2')
on conflict (fecha) do nothing;
