-- ============================================================================
-- Matutinas — Primer semestre 2026 (Enero a Junio)
-- Versión bíblica: Reina-Valera 1909 (RV1909, dominio público)
-- Texto de los versículos: api.getbible.net (traducción "valera")
-- Generado por db/_build_texts.py — Total: 181 días
-- ============================================================================

create table if not exists versiculos_dia (
  id                bigint generated always as identity primary key,
  fecha             date    not null unique,
  dia_semana        text    not null,
  tema              text    not null,
  cita              text    not null,
  libro             text    not null,
  capitulo          int     not null,
  versiculo_inicio  int     not null,
  versiculo_fin     int,
  texto             text,
  semestre          text    not null default '2026-1'
);

insert into versiculos_dia
  (fecha, dia_semana, tema, cita, libro, capitulo, versiculo_inicio, versiculo_fin, texto)
values
-- ===================== ENERO 2026 =====================
('2026-01-01','Jueves','La preparación para su regreso','1 Tesalonicenses 5:23','1 Tesalonicenses',5,23,NULL,'Y el Dios de paz os santifique en todo; para que vuestro espíritu y alma y cuerpo sea guardado entero sin reprensión para la venida de nuestro Señor Jesucristo.'),
('2026-01-02','Viernes','La preparación para su regreso','1 Juan 2:28','1 Juan',2,28,NULL,'Y ahora, hijitos, perseverad en él; para que cuando apareciere, tengamos confianza, y no seamos confundidos de él en su venida.'),
('2026-01-03','Sábado','La preparación para su regreso','Apocalipsis 14:12','Apocalipsis',14,12,NULL,'Aquí está la paciencia de los santos; aquí están los que guardan los mandamientos de Dios, y la fe de Jesús.'),
('2026-01-04','Domingo','Consejos a los hombres cristianos','Job 11:11','Job',11,11,NULL,'Porque él conoce á los hombres vanos: ve asimismo la iniquidad, ¿y no hará caso?'),
('2026-01-05','Lunes','Consejos a los hombres cristianos','Salmos 36:7','Salmos',36,7,NULL,'¡Cuán ilustre, oh Dios, es tu misericordia! Por eso los hijos de los hombres se amparan bajo la sombra de tus alas.'),
('2026-01-06','Martes','Consejos a los hombres cristianos','Salmos 58:1','Salmos',58,1,NULL,'Oh congregación, ¿pronunciáis en verdad justicia? ¿juzgáis rectamente, hijos de los hombres?'),
('2026-01-07','Miércoles','Consejos a los hombres cristianos','Salmos 90:3','Salmos',90,3,NULL,'Vuelves al hombre hasta ser quebrantado, y dices: Convertíos, hijos de los hombres.'),
('2026-01-08','Jueves','Consejos a los hombres cristianos','Salmos 24:1','Salmos',24,1,NULL,'De Jehová es la tierra y su plenitud; el mundo, y los que en él habitan.'),
('2026-01-09','Viernes','Consejos a los hombres cristianos','Proverbios 29:10','Proverbios',29,10,NULL,'Los hombres sanguinarios aborrecen al perfecto: mas los rectos buscan su contentamiento.'),
('2026-01-10','Sábado','Consejos a los hombres cristianos','Mateo 5:16','Mateo',5,16,NULL,'Así alumbre vuestra luz delante de los hombres, para que vean vuestras obras buenas, y glorifiquen á vuestro Padre que está en los cielos.'),
('2026-01-11','Domingo','Consejos a los hombres cristianos','1 Corintios 7:3','1 Corintios',7,3,NULL,'El marido pague á la mujer la debida benevolencia; y asimismo la mujer al marido.'),
('2026-01-12','Lunes','Consejos a los hombres cristianos','1 Corintios 7:27','1 Corintios',7,27,NULL,'¿Estás ligado á mujer? no procures soltarte. ¿Estás suelto de mujer? no procures mujer.'),
('2026-01-13','Martes','Consejos a los hombres cristianos','Efesios 5:23','Efesios',5,23,NULL,'Porque el marido es cabeza de la mujer, así como Cristo es cabeza de la iglesia; y él es el que da la salud al cuerpo.'),
('2026-01-14','Miércoles','Consejos a los hombres cristianos','Efesios 5:25','Efesios',5,25,NULL,'Maridos, amad á vuestras mujeres, así como Cristo amó á la iglesia, y se entregó á sí mismo por ella,'),
('2026-01-15','Jueves','Consejos a los hombres cristianos','Efesios 5:28','Efesios',5,28,NULL,'Así también los maridos deben amar á sus mujeres como á sus mismos cuerpos. El que ama á su mujer, á sí mismo se ama.'),
('2026-01-16','Viernes','Consejos a los hombres cristianos','Colosenses 3:19','Colosenses',3,19,NULL,'Maridos, amad á vuestras mujeres, y no seáis desapacibles con ellas.'),
('2026-01-17','Sábado','Consejos a los hombres cristianos','1 Pedro 3:7','1 Pedro',3,7,NULL,'Vosotros maridos, semejantemente, habitad con ellas según ciencia, dando honor á la mujer como á vaso más frágil, y como á herederas juntamente de la gracia de la vida; para que vuestras oraciones no sean impedidas.'),
('2026-01-18','Domingo','Consejos a las mujeres cristianas','Deuteronomio 22:5','Deuteronomio',22,5,NULL,'No vestirá la mujer hábito de hombre, ni el hombre vestirá ropa de mujer; porque abominación es á Jehová tu Dios cualquiera que esto hace.'),
('2026-01-19','Lunes','Consejos a las mujeres cristianas','Proverbios 12:4','Proverbios',12,4,NULL,'La mujer virtuosa corona es de su marido: mas la mala, como carcoma en sus huesos.'),
('2026-01-20','Martes','Consejos a las mujeres cristianas','Proverbios 14:1','Proverbios',14,1,NULL,'La mujer sabia edifica su casa: mas la necia con sus manos la derriba.'),
('2026-01-21','Miércoles','Consejos a las mujeres cristianas','Proverbios 31:30','Proverbios',31,30,NULL,'Engañosa es la gracia, y vana la hermosura: la mujer que teme á Jehová, ésa será alabada.'),
('2026-01-22','Jueves','Consejos a las mujeres cristianas','1 Corintios 11:3','1 Corintios',11,3,NULL,'Mas quiero que sepáis, que Cristo es la cabeza de todo varón; y el varón es la cabeza de la mujer; y Dios la cabeza de Cristo.'),
('2026-01-23','Viernes','Consejos a las mujeres cristianas','1 Corintios 11:5','1 Corintios',11,5,NULL,'Mas toda mujer que ora ó profetiza no cubierta su cabeza, afrenta su cabeza; porque lo mismo es que si se rayese.'),
('2026-01-24','Sábado','Consejos a las mujeres cristianas','1 Corintios 11:6','1 Corintios',11,6,NULL,'Porque si la mujer no se cubre, trasquílese también: y si es deshonesto á la mujer trasquilarse ó raerse, cúbrase.'),
('2026-01-25','Domingo','Consejos a las mujeres cristianas','1 Corintios 11:10','1 Corintios',11,10,NULL,'Por lo cual, la mujer debe tener señal de potestad sobre su cabeza, por causa de los ángeles.'),
('2026-01-26','Lunes','Consejos a las mujeres cristianas','1 Corintios 11:13','1 Corintios',11,13,NULL,'Juzgad vosotros mismos: ¿es honesto orar la mujer á Dios no cubierta?'),
('2026-01-27','Martes','Consejos a las mujeres cristianas','1 Timoteo 2:9','1 Timoteo',2,9,NULL,'Asimismo también las mujeres, ataviándose en hábito honesto, con vergüenza y modestia; no con cabellos encrespados, ú oro, ó perlas, ó vestidos costosos,'),
('2026-01-28','Miércoles','Consejos a las mujeres cristianas','1 Timoteo 2:10','1 Timoteo',2,10,NULL,'Sino de buenas obras, como conviene á mujeres que profesan piedad.'),
('2026-01-29','Jueves','Consejos a las mujeres cristianas','1 Timoteo 2:12','1 Timoteo',2,12,NULL,'Porque no permito á la mujer enseñar, ni tomar autoridad sobre el hombre, sino estar en silencio.'),
('2026-01-30','Viernes','Consejos a las mujeres cristianas','Tito 2:3','Tito',2,3,NULL,'Las viejas, asimismo, se distingan en un porte santo; no calumniadoras, no dadas á mucho vino, maestras de honestidad:'),
('2026-01-31','Sábado','Consejos a las mujeres cristianas','Tito 2:4','Tito',2,4,NULL,'Que enseñen á las mujeres jóvenes á ser prudentes, á que amen á sus maridos, á que amen á sus hijos,'),
-- ===================== FEBRERO 2026 =====================
('2026-02-01','Domingo','Consejos a las mujeres cristianas','Tito 2:5','Tito',2,5,NULL,'A ser templadas, castas, que tengan cuidado de la casa, buenas, sujetas á sus maridos; porque la palabra de Dios no sea blasfemada.'),
('2026-02-02','Lunes','Consejos a las mujeres cristianas','1 Corintios 14:34','1 Corintios',14,34,NULL,'Vuestras mujeres callen en las congregaciones; porque no les es permitido hablar, sino que estén sujetas, como también la ley dice.'),
('2026-02-03','Martes','Consejos a las mujeres cristianas','Proverbios 31:20','Proverbios',31,20,NULL,'Alargó su mano al pobre, y extendió sus manos al menesteroso.'),
('2026-02-04','Miércoles','Consejos a los jóvenes cristianos','Eclesiastés 11:10','Eclesiastés',11,10,NULL,'Quita pues el enojo de tu corazón, y aparta el mal de tu carne: porque la mocedad y la juventud son vanidad.'),
('2026-02-05','Jueves','Consejos a los jóvenes cristianos','Isaías 40:30','Isaías',40,30,NULL,'Los mancebos se fatigan y se cansan, los mozos flaquean y caen:'),
('2026-02-06','Viernes','Consejos a los jóvenes cristianos','Isaías 40:31','Isaías',40,31,NULL,'Mas los que esperan á Jehová tendrán nuevas fuerzas; levantarán las alas como águilas; correrán, y no se cansarán; caminarán, y no se fatigarán.'),
('2026-02-07','Sábado','Consejos a los jóvenes cristianos','1 Pedro 5:5','1 Pedro',5,5,NULL,'Igualmente, mancebos, sed sujetos á los ancianos; y todos sumisos unos á otros, revestíos de humildad; porque Dios resiste á los soberbios, y da gracia á los humildes.'),
('2026-02-08','Domingo','Consejos a las señoritas cristianas','Deuteronomio 22:5','Deuteronomio',22,5,NULL,'No vestirá la mujer hábito de hombre, ni el hombre vestirá ropa de mujer; porque abominación es á Jehová tu Dios cualquiera que esto hace.'),
('2026-02-09','Lunes','Consejos a las señoritas cristianas','Eclesiastés 12:1','Eclesiastés',12,1,NULL,'Y acuérdate de tu Criador en los días de tu juventud, antes que vengan los malos días, y lleguen los años, de los cuales digas, No tengo en ellos contentamiento;'),
('2026-02-10','Martes','Consejos a las señoritas cristianas','Romanos 13:14','Romanos',13,14,NULL,'Mas vestíos del Señor Jesucristo, y no hagáis caso de la carne en sus deseos.'),
('2026-02-11','Miércoles','Consejos a las señoritas cristianas','2 Corintios 8:21','2 Corintios',8,21,NULL,'Procurando las cosas honestas, no sólo delante del Señor, mas aun delante de los hombres.'),
('2026-02-12','Jueves','Consejos a las señoritas cristianas','1 Timoteo 3:11','1 Timoteo',3,11,NULL,'Las mujeres asimismo, honestas, no detractoras, templadas, fieles en todo.'),
('2026-02-13','Viernes','Consejos a las señoritas cristianas','1 Timoteo 5:14','1 Timoteo',5,14,NULL,'Quiero pues, que las que son jóvenes se casen, críen hijos, gobiernen la casa; que ninguna ocasión den al adversario para maldecir.'),
('2026-02-14','Sábado','Consejos a las señoritas cristianas','1 Timoteo 5:15','1 Timoteo',5,15,NULL,'Porque ya algunas han vuelto atrás en pos de Satanás.'),
('2026-02-15','Domingo','La ley de Dios o moral','Deuteronomio 4:12','Deuteronomio',4,12,NULL,'Y habló Jehová con vosotros de en medio del fuego: oisteis la voz de sus palabras, mas á excepción de oir la voz, ninguna figura visteis:'),
('2026-02-16','Lunes','La ley de Dios o moral','Éxodo 31:18','Éxodo',31,18,NULL,'Y dió á Moisés, como acabó de hablar con él en el monte de Sinaí, dos tablas del testimonio, tablas de piedra escritas con el dedo de Dios.'),
('2026-02-17','Martes','La ley de Dios o moral','Éxodo 23:12','Éxodo',23,12,NULL,'Seis días harás tus negocios, y al séptimo día holgarás, á fin que descanse tu buey y tu asno, y tome refrigerio el hijo de tu sierva, y el extranjero.'),
('2026-02-18','Miércoles','La ley de Dios o moral','Salmos 19:7','Salmos',19,7,NULL,'La ley de Jehová es perfecta, que vuelve el alma: el testimonio de Jehová, fiel, que hace sabio al pequeño.'),
('2026-02-19','Jueves','La ley de Dios o moral','Mateo 5:17-18','Mateo',5,17,18,'No penséis que he venido para abrogar la ley ó los profetas: no he venido para abrogar, sino á cumplir. Porque de cierto os digo, que hasta que perezca el cielo y la tierra, ni una jota ni un tilde perecerá de la ley, hasta que todas las cosas sean hechas.'),
('2026-02-20','Viernes','La ley de Dios o moral','Santiago 2:12','Santiago',2,12,NULL,'Así hablad, y así obrad, como los que habéis de ser juzgados por la ley de libertad.'),
('2026-02-21','Sábado','La ley de Dios o moral','Romanos 7:14','Romanos',7,14,NULL,'Porque sabemos que la ley es espiritual; mas yo soy carnal, vendido á sujeción del pecado.'),
('2026-02-22','Domingo','La ley de Dios o moral','Romanos 3:27','Romanos',3,27,NULL,'¿Dónde pues está la jactancia? Es excluída. ¿Por cuál ley? ¿de las obras? No; mas por la ley de la fe.'),
('2026-02-23','Lunes','La ley de Dios o moral','Romanos 7:12','Romanos',7,12,NULL,'De manera que la ley á la verdad es santa, y el mandamiento santo, y justo, y bueno.'),
('2026-02-24','Martes','La ley de Dios o moral','Deuteronomio 5:22','Deuteronomio',5,22,NULL,'Estas palabras habló Jehová á toda vuestra congregación en el monte, de en medio del fuego, de la nube y de la oscuridad, á gran voz: y no añadió más. Y escribiólas en dos tablas de piedra, las cuales me dió á mí.'),
('2026-02-25','Miércoles','La ley de Dios o moral','Éxodo 25:21','Éxodo',25,21,NULL,'Y pondrás la cubierta encima del arca, y en el arca pondrás el testimonio que yo te daré.'),
('2026-02-26','Jueves','La ley de Dios o moral','1 Reyes 8:9','1 Reyes',8,9,NULL,'En el arca ninguna cosa había más de las dos tablas de piedra que había allí puesto Moisés en Horeb, donde Jehová hizo la alianza con los hijos de Israel, cuando salieron de la tierra de Egipto.'),
('2026-02-27','Viernes','La ley de Dios o moral','Éxodo 20:3-5','Éxodo',20,3,5,'No tendrás dioses ajenos delante de mí. No te harás imagen, ni ninguna semejanza de cosa que esté arriba en el cielo, ni abajo en la tierra, ni en las aguas debajo de la tierra: No te inclinarás á ellas, ni las honrarás; porque yo soy Jehová tu Dios, fuerte, celoso, que visito la maldad de los padres sobre los hijos, sobre los terceros y sobre los cuartos, á los que me aborrecen,'),
('2026-02-28','Sábado','La ley de Dios o moral','Éxodo 20:6-10','Éxodo',20,6,10,'Y que hago misericordia en millares á los que me aman, y guardan mis mandamientos. No tomarás el nombre de Jehová tu Dios en vano; porque no dará por inocente Jehová al que tomare su nombre en vano. Acordarte has del día del reposo, para santificarlo: Seis días trabajarás, y harás toda tu obra; Mas el séptimo día será reposo para Jehová tu Dios: no hagas en él obra alguna, tú, ni tu hijo, ni tu hija, ni tu siervo, ni tu criada ni tu bestia, ni tu extranjero que está dentro de tus puertas:'),
-- ===================== MARZO 2026 =====================
('2026-03-01','Domingo','La ley de Moisés o ceremonial','Deuteronomio 1:6','Deuteronomio',1,6,NULL,'Jehová nuestro Dios nos habló en Horeb, diciendo: Harto habéis estado en este monte;'),
('2026-03-02','Lunes','La ley de Moisés o ceremonial','Deuteronomio 31:24','Deuteronomio',31,24,NULL,'Y como acabó Moisés de escribir las palabras de esta ley en un libro hasta concluirse,'),
('2026-03-03','Martes','La ley de Moisés o ceremonial','Deuteronomio 31:25-26','Deuteronomio',31,25,26,'Mandó Moisés á los Levitas que llevaban el arca del pacto de Jehová, diciendo: Tomad este libro de la ley, y ponedlo al lado del arca del pacto de Jehová vuestro Dios, y esté allí por testigo contra ti.'),
('2026-03-04','Miércoles','La ley de Moisés o ceremonial','Hebreos 7:19','Hebreos',7,19,NULL,'Porque nada perfeccionó la ley; mas hízolo la introducción de mejor esperanza, por la cual nos acercamos á Dios.'),
('2026-03-05','Jueves','La ley de Moisés o ceremonial','Efesios 2:15','Efesios',2,15,NULL,'Dirimiendo en su carne las enemistades, la ley de los mandamientos en orden á ritos, para edificar en sí mismo los dos en un nuevo hombre, haciendo la paz,'),
('2026-03-06','Viernes','La ley de Moisés o ceremonial','Colosenses 2:14','Colosenses',2,14,NULL,'Rayendo la cédula de los ritos que nos era contraria, que era contra nosotros, quitándola de en medio y enclavándola en la cruz;'),
('2026-03-07','Sábado','La ley de Moisés o ceremonial','Gálatas 5:1','Gálatas',5,1,NULL,'Estad, pues, firmes en la libertad con que Cristo nos hizo libres, y no volváis otra vez á ser presos en el yugo de servidumbre.'),
('2026-03-08','Domingo','La ley de Moisés o ceremonial','Gálatas 3:10','Gálatas',3,10,NULL,'Porque todos los que son de las obras de la ley, están bajo de maldición. Porque escrito está: Maldito todo aquel que no permaneciere en todas las cosas que están escritas en el libro de la ley, para hacerlas.'),
('2026-03-09','Lunes','La ley de Moisés o ceremonial','Ezequiel 20:25','Ezequiel',20,25,NULL,'Por eso yo también les dí ordenanzas no buenas, y derechos por los cuales no viviesen;'),
('2026-03-10','Martes','La ley de Moisés o ceremonial','Deuteronomio 31:24','Deuteronomio',31,24,NULL,'Y como acabó Moisés de escribir las palabras de esta ley en un libro hasta concluirse,'),
('2026-03-11','Miércoles','La ley de Moisés o ceremonial','Deuteronomio 31:26','Deuteronomio',31,26,NULL,'Tomad este libro de la ley, y ponedlo al lado del arca del pacto de Jehová vuestro Dios, y esté allí por testigo contra ti.'),
('2026-03-12','Jueves','La ley de Moisés o ceremonial','Hebreos 7:16','Hebreos',7,16,NULL,'El cual no es hecho conforme á la ley del mandamiento carnal, sino según la virtud de vida indisoluble;'),
('2026-03-13','Viernes','La ley de Moisés o ceremonial','Hebreos 7:28','Hebreos',7,28,NULL,'Porque la ley constituye sacerdotes á hombres flacos; mas la palabra del juramento, después de la ley, constituye al Hijo, hecho perfecto para siempre.'),
('2026-03-14','Sábado','La ley de Moisés o ceremonial','Hechos 15:5','Hechos',15,5,NULL,'Mas algunos de la secta de los Fariseos, que habían creído, se levantaron, diciendo: Que es menester circuncidarlos, y mandarles que guarden la ley de Moisés.'),
('2026-03-15','Domingo','Profecías cumplidas','Miqueas 5:2','Miqueas',5,2,NULL,'Mas tú, Beth-lehem Ephrata, pequeña para ser en los millares de Judá, de ti me saldrá el que será Señor en Israel; y sus salidas son desde el principio, desde los días del siglo.'),
('2026-03-16','Lunes','Profecías cumplidas','Mateo 2:1','Mateo',2,1,NULL,'Y como fué nacido Jesús en Bethlehem de Judea en días del rey Herodes, he aquí unos magos vinieron del oriente á Jerusalem,'),
('2026-03-17','Martes','Profecías cumplidas','Isaías 7:14','Isaías',7,14,NULL,'Por tanto el mismo Señor os dará señal: He aquí que la virgen concebirá, y parirá hijo, y llamará su nombre Emmanuel.'),
('2026-03-18','Miércoles','Profecías cumplidas','Mateo 1:23','Mateo',1,23,NULL,'He aquí la virgen concebirá y parirá un hijo, y llamarás su nombre Emmanuel, que declarado, es: Con nosotros Dios.'),
('2026-03-19','Jueves','Profecías cumplidas','Oseas 11:1','Oseas',11,1,NULL,'Cuando Israel era muchacho, yo lo amé, y de Egipto llamé á mi hijo.'),
('2026-03-20','Viernes','Profecías cumplidas','Mateo 2:15','Mateo',2,15,NULL,'Y estuvo allá hasta la muerte de Herodes: para que se cumpliese lo que fué dicho por el Señor, por el profeta que dijo: De Egipto llamé á mi Hijo.'),
('2026-03-21','Sábado','Profecías cumplidas','Isaías 53:4','Isaías',53,4,NULL,'Ciertamente llevó él nuestras enfermedades, y sufrió nuestros dolores; y nosotros le tuvimos por azotado, por herido de Dios y abatido.'),
('2026-03-22','Domingo','Profecías cumplidas','Mateo 8:17','Mateo',8,17,NULL,'Para que se cumpliese lo que fué dicho por el profeta Isaías, que dijo: El mismo tomó nuestras enfermedades, y llevó nuestras dolencias.'),
('2026-03-23','Lunes','Profecías cumplidas','Salmos 78:2','Salmos',78,2,NULL,'Abriré mi boca en parábola; hablaré cosas reservadas de antiguo:'),
('2026-03-24','Martes','Profecías cumplidas','Mateo 13:34','Mateo',13,34,NULL,'Todo esto habló Jesús por parábolas á las gentes, y sin parábolas no les hablaba:'),
('2026-03-25','Miércoles','Profecías cumplidas','Isaías 40:11','Isaías',40,11,NULL,'Como pastor apacentará su rebaño; en su brazo cogerá los corderos, y en su seno los llevará; pastoreará suavemente las paridas.'),
('2026-03-26','Jueves','Profecías cumplidas','Juan 10:14','Juan',10,14,NULL,'Yo soy el buen pastor; y conozco mis ovejas, y las mías me conocen.'),
('2026-03-27','Viernes','Profecías cumplidas','Zacarías 11:13','Zacarías',11,13,NULL,'Y díjome Jehová: Echalo al tesorero, hermoso precio con que me han apreciado. Y tomé las treinta piezas de plata, y echélas en la casa de Jehová al tesorero.'),
('2026-03-28','Sábado','Profecías cumplidas','Mateo 27:3','Mateo',27,3,NULL,'Entonces Judas, el que le había entregado, viendo que era condenado, volvió arrepentido las treinta piezas de plata á los príncipes de los sacerdotes y á los ancianos,'),
('2026-03-29','Domingo','Los impedimentos para la oración','Isaías 59:2','Isaías',59,2,NULL,'Mas vuestras iniquidades han hecho división entre vosotros y vuestro Dios, y vuestros pecados han hecho ocultar su rostro de vosotros, para no oir.'),
('2026-03-30','Lunes','Los impedimentos para la oración','Salmos 66:18','Salmos',66,18,NULL,'Si en mi corazón hubiese yo mirado á la iniquidad, el Señor no me oyera.'),
('2026-03-31','Martes','Los impedimentos para la oración','Proverbios 28:9','Proverbios',28,9,NULL,'El que aparta su oído para no oir la ley, su oración también es abominable.'),
-- ===================== ABRIL 2026 =====================
('2026-04-01','Miércoles','Los impedimentos para la oración','1 Pedro 3:7','1 Pedro',3,7,NULL,'Vosotros maridos, semejantemente, habitad con ellas según ciencia, dando honor á la mujer como á vaso más frágil, y como á herederas juntamente de la gracia de la vida; para que vuestras oraciones no sean impedidas.'),
('2026-04-02','Jueves','Los impedimentos para la oración','Marcos 11:25','Marcos',11,25,NULL,'Y cuando estuviereis orando, perdonad, si tenéis algo contra alguno, para que vuestro Padre que está en los cielos os perdone también á vosotros vuestras ofensas.'),
('2026-04-03','Viernes','Los impedimentos para la oración','Marcos 11:26','Marcos',11,26,NULL,'Porque si vosotros no perdonareis, tampoco vuestro Padre que está en los cielos os perdonará vuestras ofensas.'),
('2026-04-04','Sábado','Los impedimentos para la oración','2 Crónicas 7:14','2 Crónicas',7,14,NULL,'Si se humillare mi pueblo, sobre los cuales ni nombre es invocado, y oraren, y buscaren mi rostro, y se convirtieren de sus malos caminos; entonces yo oiré desde los cielos, y perdonaré sus pecados, y sanaré su tierra.'),
('2026-04-05','Domingo','La palabra escrita','2 Pedro 1:19','2 Pedro',1,19,NULL,'Tenemos también la palabra profética más permanente, á la cual hacéis bien de estar atentos como á una antorcha que alumbra en lugar oscuro hasta que el día esclarezca, y el lucero de la mañana salga en vuestros corazones:'),
('2026-04-06','Lunes','La palabra escrita','2 Pedro 1:20','2 Pedro',1,20,NULL,'Entendiendo primero esto, que ninguna profecía de la Escritura es de particular interpretación;'),
('2026-04-07','Martes','La palabra escrita','2 Pedro 1:21','2 Pedro',1,21,NULL,'Porque la profecía no fué en los tiempos pasados traída por voluntad humana, sino los santos hombres de Dios hablaron siendo inspirados del Espíritu Santo.'),
('2026-04-08','Miércoles','La palabra escrita','Amós 3:7','Amós',3,7,NULL,'Porque no hará nada el Señor Jehová, sin que revele su secreto á sus siervos los profetas.'),
('2026-04-09','Jueves','La palabra escrita','Deuteronomio 29:29','Deuteronomio',29,29,NULL,'Las cosas secretas pertenecen á Jehová nuestro Dios: mas las reveladas son para nosotros y para nuestros hijos por siempre, para que cumplamos todas las palabras de esta ley.'),
('2026-04-10','Viernes','La palabra escrita','Hebreos 2:2','Hebreos',2,2,NULL,'Porque si la palabra dicha por los ángeles fué firme, y toda rebelión y desobediencia recibió justa paga de retribución,'),
('2026-04-11','Sábado','La palabra escrita','2 Timoteo 3:16','2 Timoteo',3,16,NULL,'Toda Escritura es inspirada divinamente y útil para enseñar, para redargüir, para corregir, para instituir en justicia,'),
('2026-04-12','Domingo','Propósito de la palabra','2 Timoteo 3:17','2 Timoteo',3,17,NULL,'Para que el hombre de Dios sea perfecto, enteramente instruído para toda buena obra.'),
('2026-04-13','Lunes','Propósito de la palabra','Salmos 119:9-11','Salmos',119,9,11,'¿Con qué limpiará el joven su camino? Con guardar tu palabra. Con todo mi corazón te he buscado: no me dejes divagar de tus mandamientos. En mi corazón he guardado tus dichos, para no pecar contra ti.'),
('2026-04-14','Martes','Propósito de la palabra','1 Pedro 1:23','1 Pedro',1,23,NULL,'Siendo renacidos, no de simiente corruptible, sino de incorruptible, por la palabra de Dios, que vive y permanece para siempre.'),
('2026-04-15','Miércoles','Propósito de la palabra','Juan 17:17','Juan',17,17,NULL,'Santifícalos en tu verdad: tu palabra es verdad.'),
('2026-04-16','Jueves','Propósito de la palabra','Juan 15:3','Juan',15,3,NULL,'Ya vosotros sois limpios por la palabra que os he hablado.'),
('2026-04-17','Viernes','Propósito de la palabra','Deuteronomio 6:24','Deuteronomio',6,24,NULL,'Y mandónos Jehová que ejecutásemos todos estos estatutos, y que temamos á Jehová nuestro Dios, porque nos vaya bien todos los días, y para que nos dé vida, como hoy.'),
('2026-04-18','Sábado','Propósito de la palabra','Romanos 15:4','Romanos',15,4,NULL,'Porque las cosas que antes fueron escritas, para nuestra enseñanza fueron escritas; para que por la paciencia, y por la consolación de las Escrituras, tengamos esperanza.'),
('2026-04-19','Domingo','El estudio de la palabra','1 Pedro 2:2','1 Pedro',2,2,NULL,'Desead, como niños recién nacidos, la leche espiritual, sin engaño, para que por ella crezcáis en salud:'),
('2026-04-20','Lunes','El estudio de la palabra','2 Timoteo 2:15','2 Timoteo',2,15,NULL,'Procura con diligencia presentarte á Dios aprobado, como obrero que no tiene de qué avergonzarse, que traza bien la palabra de verdad.'),
('2026-04-21','Martes','El estudio de la palabra','Hechos 17:11','Hechos',17,11,NULL,'Y fueron éstos más nobles que los que estaban en Tesalónica, pues recibieron la palabra con toda solicitud, escudriñando cada día las Escrituras, si estas cosas eran así.'),
('2026-04-22','Miércoles','El estudio de la palabra','2 Timoteo 3:15','2 Timoteo',3,15,NULL,'Y que desde la niñez has sabido las Sagradas Escrituras, las cuales te pueden hacer sabio para la salud por la fe que es en Cristo Jesús.'),
('2026-04-23','Jueves','El estudio de la palabra','Salmos 119:105','Salmos',119,105,NULL,'Lámpara es á mis pies tu palabra, y lumbrera á mi camino.'),
('2026-04-24','Viernes','El estudio de la palabra','Salmos 119:130','Salmos',119,130,NULL,'El principio de tus palabras alumbra; hace entender á los simples.'),
('2026-04-25','Sábado','El estudio de la palabra','Juan 8:31','Juan',8,31,NULL,'Y decía Jesús á los Judíos que le habían creído: Si vosotros permaneciereis en mi palabra, seréis verdaderamente mis discípulos;'),
('2026-04-26','Domingo','La verdadera doctrina','Santiago 1:26','Santiago',1,26,NULL,'Si alguno piensa ser religioso entre vosotros, y no refrena su lengua, sino engañando su corazón, la religión del tal es vana.'),
('2026-04-27','Lunes','La verdadera doctrina','Santiago 5:12','Santiago',5,12,NULL,'Mas sobre todo, hermanos míos, no juréis, ni por el cielo, ni por la tierra, ni por otro cualquier juramento; sino vuestro sí sea sí, y vuestro no sea no; porque no caigáis en condenación.'),
('2026-04-28','Martes','La verdadera doctrina','Proverbios 15:1','Proverbios',15,1,NULL,'La blanda respuesta quita la ira: mas la palabra áspera hace subir el furor.'),
('2026-04-29','Miércoles','La verdadera doctrina','Proverbios 15:4','Proverbios',15,4,NULL,'La sana lengua es árbol de vida: mas la perversidad en ella es quebrantamiento de espíritu.'),
('2026-04-30','Jueves','La verdadera doctrina','Mateo 12:34','Mateo',12,34,NULL,'Generación de víboras, ¿cómo podéis hablar bien, siendo malos? porque de la abundancia del corazón habla la boca.'),
-- ===================== MAYO 2026 =====================
('2026-05-01','Viernes','La verdadera doctrina','Mateo 12:35','Mateo',12,35,NULL,'El hombre bueno del buen tesoro del corazón saca buenas cosas: y el hombre malo del mal tesoro saca malas cosas.'),
('2026-05-02','Sábado','La verdadera doctrina','Colosenses 4:6','Colosenses',4,6,NULL,'Sea vuestra palabra siempre con gracia, sazonada con sal; para que sepáis cómo os conviene responder á cada uno.'),
('2026-05-03','Domingo','El evangelio gratuito','1 Corintios 9:17','1 Corintios',9,17,NULL,'Por lo cual, si lo hago de voluntad, premio tendré; mas si por fuerza, la dispensación me ha sido encargada.'),
('2026-05-04','Lunes','El evangelio gratuito','1 Corintios 9:18','1 Corintios',9,18,NULL,'¿Cuál, pues, es mi merced? Que predicando el evangelio, ponga el evangelio de Cristo de balde, para no usar mal de mi potestad en el evangelio.'),
('2026-05-05','Martes','El evangelio gratuito','1 Timoteo 6:10','1 Timoteo',6,10,NULL,'Porque el amor del dinero es la raíz de todos los males: el cual codiciando algunos, se descaminaron de la fe, y fueron traspasados de muchos dolores.'),
('2026-05-06','Miércoles','El evangelio gratuito','Isaías 55:1','Isaías',55,1,NULL,'A todos los sedientos: Venid á las aguas; y los que no tienen dinero, venid, comprad, y comed. Venid, comprad, sin dinero y sin precio, vino y leche.'),
('2026-05-07','Jueves','El evangelio gratuito','Isaías 52:3','Isaías',52,3,NULL,'Porque así dice Jehová: De balde fuisteis vendidos; por tanto, sin dinero seréis rescatados.'),
('2026-05-08','Viernes','El evangelio gratuito','Romanos 3:24','Romanos',3,24,NULL,'Siendo justificados gratuitamente por su gracia, por la redención que es en Cristo Jesús;'),
('2026-05-09','Sábado','El evangelio gratuito','Apocalipsis 21:6','Apocalipsis',21,6,NULL,'Y díjome: Hecho es. Yo soy Alpha y Omega, el principio y el fin. Al que tuviere sed, yo le daré de la fuente del agua de vida gratuitamente.'),
('2026-05-10','Domingo','Falsos predicadores','Mateo 24:11','Mateo',24,11,NULL,'Y muchos falsos profetas se levantarán y engañarán á muchos.'),
('2026-05-11','Lunes','Falsos predicadores','Mateo 24:24','Mateo',24,24,NULL,'Porque se levantarán falsos Cristos, y falsos profetas, y darán señales grandes y prodigios; de tal manera que engañarán, si es posible, aun á los escogidos.'),
('2026-05-12','Martes','Falsos predicadores','Marcos 13:22','Marcos',13,22,NULL,'Porque se levantarán falsos Cristos y falsos profetas, y darán señales y prodigios, para engañar, si se pudiese hacer, aun á los escogidos.'),
('2026-05-13','Miércoles','Falsos predicadores','Lucas 6:26','Lucas',6,26,NULL,'¡Ay de vosotros, cuando todos los hombres dijeren bien de vosotros! porque así hacían sus padres á los falsos profetas.'),
('2026-05-14','Jueves','Falsos predicadores','2 Corintios 2:17','2 Corintios',2,17,NULL,'Porque no somos como muchos, mercaderes falsos de la palabra de Dios: antes con sinceridad, como de Dios, delante de Dios, hablamos en Cristo.'),
('2026-05-15','Viernes','Falsos predicadores','2 Corintios 11:13','2 Corintios',11,13,NULL,'Porque éstos son falsos apóstoles, obreros fraudulentos, transfigurándose en apóstoles de Cristo.'),
('2026-05-16','Sábado','Falsos predicadores','Romanos 16:18','Romanos',16,18,NULL,'Porque los tales no sirven al Señor nuestro Jesucristo, sino á sus vientres; y con suaves palabras y bendiciones engañan los corazones de los simples.'),
('2026-05-17','Domingo','Dadivosidad','2 Corintios 9:7','2 Corintios',9,7,NULL,'Cada uno dé como propuso en su corazón: no con tristeza, ó por necesidad; porque Dios ama el dador alegre.'),
('2026-05-18','Lunes','Dadivosidad','2 Corintios 9:9','2 Corintios',9,9,NULL,'Como está escrito: Derramó, dió á los pobres; su justicia permanece para siempre.'),
('2026-05-19','Martes','Dadivosidad','2 Corintios 8:3','2 Corintios',8,3,NULL,'Pues de su grado han dado conforme á sus fuerzas, yo testifico, y aun sobre sus fuerzas;'),
('2026-05-20','Miércoles','Dadivosidad','2 Corintios 8:12','2 Corintios',8,12,NULL,'Porque si primero hay la voluntad pronta, será acepta por lo que tiene, no por lo que no tiene.'),
('2026-05-21','Jueves','Dadivosidad','Efesios 4:28','Efesios',4,28,NULL,'El que hurtaba, no hurte más; antes trabaje, obrando con sus manos lo que es bueno, para que tenga de qué dar al que padeciere necesidad.'),
('2026-05-22','Viernes','Dadivosidad','Lucas 6:38','Lucas',6,38,NULL,'Dad, y se os dará; medida buena, apretada, remecida, y rebosando darán en vuestro seno: porque con la misma medida que midiereis, os será vuelto á medir.'),
('2026-05-23','Sábado','Dadivosidad','2 Tesalonicenses 3:13','2 Tesalonicenses',3,13,NULL,'Y vosotros, hermanos, no os canséis de hacer bien.'),
('2026-05-24','Domingo','La verdad','Salmos 51:6','Salmos',51,6,NULL,'He aquí, tú amas la verdad en lo íntimo: y en lo secreto me has hecho comprender sabiduría.'),
('2026-05-25','Lunes','La verdad','Juan 16:13','Juan',16,13,NULL,'Pero cuando viniere aquel Espíritu de verdad, él os guiará á toda verdad; porque no hablará de sí mismo, sino que hablará todo lo que oyere, y os hará saber las cosas que han de venir.'),
('2026-05-26','Martes','La verdad','Juan 17:17','Juan',17,17,NULL,'Santifícalos en tu verdad: tu palabra es verdad.'),
('2026-05-27','Miércoles','La verdad','Juan 8:32','Juan',8,32,NULL,'Y conoceréis la verdad, y la verdad os libertará.'),
('2026-05-28','Jueves','La verdad','Zacarías 8:16','Zacarías',8,16,NULL,'Estas son las cosas que habéis de hacer: Hablad verdad cada cual con su prójimo; juzgad en vuestras puertas verdad y juicio de paz:'),
('2026-05-29','Viernes','La verdad','Efesios 4:25','Efesios',4,25,NULL,'Por lo cual, dejada la mentira, hablad verdad cada uno con su prójimo; porque somos miembros los unos de los otros.'),
('2026-05-30','Sábado','La verdad','Efesios 4:15','Efesios',4,15,NULL,'Antes siguiendo la verdad en amor, crezcamos en todas cosas en aquel que es la cabeza, á saber, Cristo;'),
('2026-05-31','Domingo','La perfección','Mateo 5:48','Mateo',5,48,NULL,'Sed, pues, vosotros perfectos, como vuestro Padre que está en los cielos es perfecto.'),
-- ===================== JUNIO 2026 =====================
('2026-06-01','Lunes','La perfección','Efesios 5:27','Efesios',5,27,NULL,'Para presentársela gloriosa para sí, una iglesia que no tuviese mancha ni arruga, ni cosa semejante; sino que fuese santa y sin mancha.'),
('2026-06-02','Martes','La perfección','Apocalipsis 14:5','Apocalipsis',14,5,NULL,'Y en sus bocas no ha sido hallado engaño; porque ellos son sin mácula delante del trono de Dios.'),
('2026-06-03','Miércoles','La perfección','Tito 2:14','Tito',2,14,NULL,'Que se dió á sí mismo por nosotros para redimirnos de toda iniquidad, y limpiar para sí un pueblo propio, celoso de buenas obras.'),
('2026-06-04','Jueves','La perfección','2 Timoteo 3:16-17','2 Timoteo',3,16,17,'Toda Escritura es inspirada divinamente y útil para enseñar, para redargüir, para corregir, para instituir en justicia, Para que el hombre de Dios sea perfecto, enteramente instruído para toda buena obra.'),
('2026-06-05','Viernes','La perfección','1 Juan 2:6','1 Juan',2,6,NULL,'El que dice que está en él, debe andar como él anduvo.'),
('2026-06-06','Sábado','La perfección','Judas 1:24','Judas',1,24,NULL,'A aquel, pues, que es poderoso para guardaros sin caída, y presentaros delante de su gloria irreprensibles, con grande alegría,'),
('2026-06-07','Domingo','Unidad de la hermandad','Juan 17:21','Juan',17,21,NULL,'Para que todos sean una cosa; como tú, oh Padre, en mí, y yo en ti, que también ellos sean en nosotros una cosa: para que el mundo crea que tú me enviaste.'),
('2026-06-08','Lunes','Unidad de la hermandad','Juan 17:23','Juan',17,23,NULL,'Yo en ellos, y tú en mí, para que sean consumadamente una cosa; que el mundo conozca que tú me enviaste, y que los has amado, como también á mí me has amado.'),
('2026-06-09','Martes','Unidad de la hermandad','1 Corintios 1:10','1 Corintios',1,10,NULL,'Os ruego pues, hermanos, por el nombre de nuestro Señor Jesucristo, que habléis todos una misma cosa, y que no haya entre vosotros disensiones, antes seáis perfectamente unidos en una misma mente y en un mismo parecer.'),
('2026-06-10','Miércoles','Unidad de la hermandad','Efesios 4:13','Efesios',4,13,NULL,'Hasta que todos lleguemos á la unidad de la fe y del conocimiento del Hijo de Dios, á un varón perfecto, á la medida de la edad de la plenitud de Cristo:'),
('2026-06-11','Jueves','Unidad de la hermandad','1 Pedro 3:8','1 Pedro',3,8,NULL,'Y finalmente, sed todos de un mismo corazón, compasivos, amándoos fraternalmente, misericordiosos, amigables;'),
('2026-06-12','Viernes','Unidad de la hermandad','Salmos 133:1','Salmos',133,1,NULL,'¡Mirad cuán bueno y cuán delicioso es habitar los hermanos igualmente en uno!'),
('2026-06-13','Sábado','Unidad de la hermandad','2 Corintios 13:11','2 Corintios',13,11,NULL,'Resta, hermanos, que tengáis gozo, seáis perfectos, tengáis consolación, sintáis una misma cosa, tengáis paz; y el Dios de paz y de caridad será con vosotros.'),
('2026-06-14','Domingo','Obediencia','1 Samuel 15:22','1 Samuel',15,22,NULL,'Y Samuel dijo: ¿Tiene Jehová tanto contentamiento con los holocaustos y víctimas, como en obedecer á las palabras de Jehová? Ciertamente el obedecer es mejor que los sacrificios; y el prestar atención que el sebo de los carneros:'),
('2026-06-15','Lunes','Obediencia','Hechos 5:29','Hechos',5,29,NULL,'Y respondiendo Pedro y los apóstoles, dijeron: Es menester obedecer á Dios antes que á los hombres.'),
('2026-06-16','Martes','Obediencia','Hechos 4:19','Hechos',4,19,NULL,'Entonces Pedro y Juan, respondiendo, les dijeron: Juzgad si es justo delante de Dios obedecer antes á vosotros que á Dios:'),
('2026-06-17','Miércoles','Obediencia','Génesis 22:18','Génesis',22,18,NULL,'En tu simiente serán benditas todas las gentes de la tierra, por cuanto obedeciste á mi voz.'),
('2026-06-18','Jueves','Obediencia','Hechos 26:19','Hechos',26,19,NULL,'Por lo cual, oh rey Agripa, no fuí rebelde á la visión celestial:'),
('2026-06-19','Viernes','Obediencia','2 Corintios 10:5','2 Corintios',10,5,NULL,'Destruyendo consejos, y toda altura que se levanta contra la ciencia de Dios, y cautivando todo intento á la obediencia de Cristo;'),
('2026-06-20','Sábado','Obediencia','Eclesiastés 12:13','Eclesiastés',12,13,NULL,'El fin de todo el discurso oído es este: Teme á Dios, y guarda sus mandamientos; porque esto es el todo del hombre.'),
('2026-06-21','Domingo','Amor cristiano','Lucas 6:27','Lucas',6,27,NULL,'Mas á vosotros los que oís, digo: Amad á vuestros enemigos, haced bien á los que os aborrecen;'),
('2026-06-22','Lunes','Amor cristiano','Juan 13:34','Juan',13,34,NULL,'Un mandamiento nuevo os doy: Que os améis unos á otros: como os he amado, que también os améis los unos á los otros.'),
('2026-06-23','Martes','Amor cristiano','Juan 13:35','Juan',13,35,NULL,'En esto conocerán todos que sois mis discípulos, si tuviereis amor los unos con los otros.'),
('2026-06-24','Miércoles','Amor cristiano','Juan 15:12','Juan',15,12,NULL,'Este es mi mandamiento: Que os améis los unos á los otros, como yo os he amado.'),
('2026-06-25','Jueves','Amor cristiano','Efesios 5:2','Efesios',5,2,NULL,'Y andad en amor, como también Cristo nos amó, y se entregó á sí mismo por nosotros, ofrenda y sacrificio á Dios en olor suave.'),
('2026-06-26','Viernes','Amor cristiano','Romanos 13:10','Romanos',13,10,NULL,'La caridad no hace mal al prójimo: así que, el cumplimento de la ley es la caridad.'),
('2026-06-27','Sábado','Amor cristiano','Hebreos 10:24','Hebreos',10,24,NULL,'Y considerémonos los unos á los otros para provocarnos al amor y á las buenas obras;'),
('2026-06-28','Domingo','Compasivos','Hebreos 13:3','Hebreos',13,3,NULL,'Acordaos de los presos, como presos juntamente con ellos; y de los afligidos, como que también vosotros mismos sois del cuerpo.'),
('2026-06-29','Lunes','Compasivos','Salmos 35:13','Salmos',35,13,NULL,'Mas yo, cuando ellos enfermaron, me vestí de saco; afligí con ayuno mi alma, y mi oración se revolvía en mi seno.'),
('2026-06-30','Martes','Compasivos','Proverbios 19:17','Proverbios',19,17,NULL,'A Jehová empresta el que da al pobre, y él le dará su paga.');
